=== gonzalotorre/DAM2_AD/201920AD1TEj2_GarciaTorreGonzalo/xml-resources/jaxb/BindingChat/chatUsuarios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="quickChat">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="usuarios">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="usuario">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nombre" type="xs:string"/>
										<xs:element name="numeroTelefono" type="xs:string"/>
										<xs:element name="mensajeEnviados">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="mensaje" type="mensajeType"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="chats">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="chat">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="uniqueID" type="xs:string"/>
										<xs:element name="titulo" type="xs:string"/>
										<xs:element name="ultimoMensaje" type="mensajeType"/>
										<xs:element name="fechaCreacion" type="xs:date"/>
										<xs:element name="mensajes">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="mensaje" type="mensajeType"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="mensajesArchivados">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="mensaje" type="mensajeType"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="mensajeType">
		<xs:sequence>
			<xs:element name="mensajeID"/>
			<xs:element name="nombreUsuario" type="xs:string"/>
			<xs:element name="textoMensaje" type="xs:string"/>
			<xs:element name="fechaPublicacion" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== gonzalotorre/DAM2_AD/201920AD1TEj2_GarciaTorreGonzalo/charusuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<quickChat xsi:noNamespaceSchemaLocation="chatUsuarios.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<usuarios>
		<usuario>
			<nombre>String</nombre>
			<numeroTelefono>String</numeroTelefono>
			<mensajeEnviados>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajeEnviados>
		</usuario>
		<usuario>
			<nombre>String</nombre>
			<numeroTelefono>String</numeroTelefono>
			<mensajeEnviados>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajeEnviados>
		</usuario>
		<usuario>
			<nombre>String</nombre>
			<numeroTelefono>String</numeroTelefono>
			<mensajeEnviados>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajeEnviados>
		</usuario>
	</usuarios>
	<chats>
		<chat>
			<uniqueID>String</uniqueID>
			<titulo>String</titulo>
			<ultimoMensaje>
				<mensajeID>text</mensajeID>
				<nombreUsuario>String</nombreUsuario>
				<textoMensaje>String</textoMensaje>
				<fechaPublicacion>1967-08-13</fechaPublicacion>
			</ultimoMensaje>
			<fechaCreacion>1967-08-13</fechaCreacion>
			<mensajes>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajes>
			<mensajesArchivados>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajesArchivados>
		</chat>
		<chat>
			<uniqueID>String</uniqueID>
			<titulo>String</titulo>
			<ultimoMensaje>
				<mensajeID>text</mensajeID>
				<nombreUsuario>String</nombreUsuario>
				<textoMensaje>String</textoMensaje>
				<fechaPublicacion>1967-08-13</fechaPublicacion>
			</ultimoMensaje>
			<fechaCreacion>1967-08-13</fechaCreacion>
			<mensajes>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajes>
			<mensajesArchivados>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajesArchivados>
		</chat>
		<chat>
			<uniqueID>String</uniqueID>
			<titulo>String</titulo>
			<ultimoMensaje>
				<mensajeID>text</mensajeID>
				<nombreUsuario>String</nombreUsuario>
				<textoMensaje>String</textoMensaje>
				<fechaPublicacion>1967-08-13</fechaPublicacion>
			</ultimoMensaje>
			<fechaCreacion>1967-08-13</fechaCreacion>
			<mensajes>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajes>
			<mensajesArchivados>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
				<mensaje>
					<mensajeID>text</mensajeID>
					<nombreUsuario>String</nombreUsuario>
					<textoMensaje>String</textoMensaje>
					<fechaPublicacion>1967-08-13</fechaPublicacion>
				</mensaje>
			</mensajesArchivados>
		</chat>
	</chats>
</quickChat>
